"""Core validation contracts shared by lead ETL checks."""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Sequence


class Severity(str, Enum):
    """Severity domain for check failures and findings."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class CheckStatus(str, Enum):
    """Execution status for one check result."""

    PASS = "pass"
    FAIL = "fail"
    SKIP = "skip"


@dataclass
class CheckResult:
    """Standard output contract for one check execution."""

    check_id: str
    status: CheckStatus
    severity: Severity
    message: str
    ingestion_id: int | None = None
    evidence: dict[str, Any] = field(default_factory=dict)
    lineage: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert result to JSON-serializable mapping."""

        return {
            "check_id": self.check_id,
            "status": self.status.value,
            "severity": self.severity.value,
            "message": self.message,
            "ingestion_id": self.ingestion_id,
            "evidence": self.evidence,
            "lineage": self.lineage,
        }


@dataclass
class CheckContext:
    """Execution context shared across checks."""

    ingestion_id: int | None
    resources: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)

    def require_resource(self, resource_key: str) -> Any:
        """Return one required resource or raise actionable error."""

        if resource_key not in self.resources:
            raise KeyError(
                f"Recurso obrigatorio ausente: {resource_key!r}. "
                "Como corrigir: registrar o recurso em CheckContext.resources."
            )
        return self.resources[resource_key]


class Check(ABC):
    """Base contract for data-quality checks."""

    check_id: str
    description: str

    @abstractmethod
    def run(self, context: CheckContext) -> CheckResult | Sequence[CheckResult]:
        """Execute one check using the provided context."""


@dataclass(frozen=True)
class CheckReport:
    """Aggregated report generated by `CheckRunner`."""

    ingestion_id: int | None
    generated_at: datetime
    fail_on: Severity | None
    exit_code: int
    summary: dict[str, int]
    results: tuple[CheckResult, ...]

    def to_dict(self) -> dict[str, Any]:
        """Convert report to JSON-serializable mapping."""

        return {
            "ingestion_id": self.ingestion_id,
            "generated_at": self.generated_at.isoformat(),
            "fail_on": self.fail_on.value if self.fail_on else None,
            "exit_code": self.exit_code,
            "summary": dict(self.summary),
            "results": [result.to_dict() for result in self.results],
        }

