"""Validation/report helpers for TMJ ETL pipelines."""

from .framework import (
    Check,
    CheckContext,
    CheckReport,
    CheckResult,
    CheckRunner,
    CheckStatus,
    Severity,
    parse_fail_on,
    persist_check_results,
    render_report_json,
    render_report_markdown,
)
from .session_coverage_report import (
    build_session_coverage_report_payload,
    render_session_coverage_report_markdown,
    write_session_coverage_report,
)
from .checks_schema import (
    DatasetCheckConfig,
    DatasetCheckConfigError,
    SchemaCheck,
    build_schema_checks,
    load_dataset_check_configs,
)
from .checks_not_null import NotNullCheck, build_not_null_checks
from .checks_duplicates import DuplicateCheck, DuplicateCheckSpec, build_duplicate_checks
from .checks_access_control import AccessControlReconciliationCheck, AccessControlRuleFinding
from .checks_show_access_control import MissingShowAccessControlCheck, ShowAccessControlFinding
from .checks_show_optin import MissingShowOptInCheck, ShowOptInFinding
from .checks_percentages import (
    PercentBoundsCheck,
    PercentSumCheck,
    PercentSumRuleConfig,
    PercentageCheckConfig,
    PercentageCheckConfigError,
    build_percentage_checks,
    load_percentage_check_configs,
)
from .checks_cross_source import (
    CrossSourceDatasetSpec,
    CrossSourceInconsistencyCheck,
    persist_cross_source_inconsistencies,
)
from .render_dq_report import render_dq_report, render_dq_report_json
from .request_list import (
    RequestItem,
    build_missing_artifacts_list,
    render_missing_artifacts_csv,
    render_missing_artifacts_markdown,
)
from .alerts import Alert, alerts_to_dicts, generate_alerts, render_alerts_markdown
from .coverage_matrix import (
    CoverageMatrixConfigError,
    CoverageMatrixRow,
    CoverageMatrixSummaryRow,
    CoverageRequirementsConfig,
    build_coverage_matrix,
    build_coverage_matrix_payload,
    build_coverage_matrix_summary,
    coverage_matrix_rows_to_dicts,
    coverage_matrix_summary_to_dicts,
    load_coverage_requirements_config,
    required_datasets_for_session_type,
)
from .coverage_contract import (
    CoverageContract,
    CoverageContractError,
    CoverageRequirementsContract,
    DatasetCoverageRule,
    SessionCoverageContract,
    coverage_requirements_from_contract,
    load_coverage_contract,
)
from .show_coverage_evaluator import (
    CoverageMissingInput,
    CoverageReport,
    SessionCoverageStatus,
    evaluate_coverage,
    evaluate_coverage_payload,
    find_show_access_control_missing_inputs,
    find_show_optin_missing_inputs,
)

__all__ = [
    "Severity",
    "CheckStatus",
    "CheckResult",
    "CheckContext",
    "Check",
    "CheckRunner",
    "CheckReport",
    "parse_fail_on",
    "persist_check_results",
    "render_report_json",
    "render_report_markdown",
    "build_session_coverage_report_payload",
    "render_session_coverage_report_markdown",
    "write_session_coverage_report",
    "DatasetCheckConfig",
    "DatasetCheckConfigError",
    "SchemaCheck",
    "NotNullCheck",
    "DuplicateCheck",
    "DuplicateCheckSpec",
    "AccessControlReconciliationCheck",
    "AccessControlRuleFinding",
    "MissingShowAccessControlCheck",
    "ShowAccessControlFinding",
    "MissingShowOptInCheck",
    "ShowOptInFinding",
    "PercentBoundsCheck",
    "PercentSumCheck",
    "PercentSumRuleConfig",
    "PercentageCheckConfig",
    "PercentageCheckConfigError",
    "load_dataset_check_configs",
    "load_percentage_check_configs",
    "build_schema_checks",
    "build_not_null_checks",
    "build_duplicate_checks",
    "build_percentage_checks",
    "CrossSourceDatasetSpec",
    "CrossSourceInconsistencyCheck",
    "persist_cross_source_inconsistencies",
    "render_dq_report",
    "render_dq_report_json",
    "RequestItem",
    "build_missing_artifacts_list",
    "render_missing_artifacts_csv",
    "render_missing_artifacts_markdown",
    "Alert",
    "generate_alerts",
    "alerts_to_dicts",
    "render_alerts_markdown",
    "CoverageMatrixConfigError",
    "CoverageContract",
    "CoverageContractError",
    "CoverageRequirementsContract",
    "DatasetCoverageRule",
    "SessionCoverageContract",
    "load_coverage_contract",
    "coverage_requirements_from_contract",
    "CoverageMissingInput",
    "SessionCoverageStatus",
    "CoverageReport",
    "evaluate_coverage",
    "evaluate_coverage_payload",
    "find_show_access_control_missing_inputs",
    "find_show_optin_missing_inputs",
    "CoverageRequirementsConfig",
    "CoverageMatrixRow",
    "CoverageMatrixSummaryRow",
    "load_coverage_requirements_config",
    "required_datasets_for_session_type",
    "build_coverage_matrix",
    "build_coverage_matrix_summary",
    "coverage_matrix_rows_to_dicts",
    "coverage_matrix_summary_to_dicts",
    "build_coverage_matrix_payload",
]
