"""Data-quality check framework for ETL validation runs.

This module defines reusable primitives to execute validation checks in a
consistent way before marts/report generation:
- `Severity`: impact level (`info`, `warning`, `error`)
- `CheckResult`: standard check output with evidence/lineage payloads
- `Check`: base protocol for concrete checks
- `CheckRunner`: orchestrates checks and computes gate exit code
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
import json
from typing import Any, Iterable, Mapping, Sequence


class Severity(str, Enum):
    """Severity domain for check failures and findings."""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class CheckStatus(str, Enum):
    """Execution status for one check result."""

    PASS = "pass"
    FAIL = "fail"
    SKIP = "skip"


@dataclass
class CheckResult:
    """Standard output contract for one check execution.

    Message convention:
    - short statement of what happened;
    - include explicit action when failing (e.g. `Como corrigir: ...`).

    Evidence convention:
    - `evidence` should include fields used to reproduce/inspect the issue;
    - `lineage` should carry source-location references whenever available
      (for example: `source_id`, `location`, `evidence_text`).

    Args:
        check_id: Stable check identifier.
        status: Check status (`pass`, `fail`, `skip`).
        severity: Severity level of this result.
        message: Actionable user-facing message.
        ingestion_id: Ingestion execution identifier.
        evidence: Optional structured evidence payload.
        lineage: Optional source/location lineage payload.
    """

    check_id: str
    status: CheckStatus
    severity: Severity
    message: str
    ingestion_id: int | None = None
    evidence: dict[str, Any] = field(default_factory=dict)
    lineage: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert result to JSON-serializable mapping."""

        return {
            "check_id": self.check_id,
            "status": self.status.value,
            "severity": self.severity.value,
            "message": self.message,
            "ingestion_id": self.ingestion_id,
            "evidence": self.evidence,
            "lineage": self.lineage,
        }


@dataclass
class CheckContext:
    """Execution context shared across checks.

    Args:
        ingestion_id: Ingestion execution identifier under validation.
        resources: Runtime objects required by checks (e.g. DB session).
        metadata: Mutable key-value store shared between checks.
    """

    ingestion_id: int | None
    resources: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)

    def require_resource(self, resource_key: str) -> Any:
        """Return one required resource or raise actionable error.

        Args:
            resource_key: Resource key expected in `resources`.

        Returns:
            Resource object.

        Raises:
            KeyError: If key is missing.
        """

        if resource_key not in self.resources:
            raise KeyError(
                f"Recurso obrigatorio ausente: {resource_key!r}. "
                "Como corrigir: registrar o recurso em CheckContext.resources."
            )
        return self.resources[resource_key]


class Check(ABC):
    """Base contract for data-quality checks."""

    check_id: str
    description: str

    @abstractmethod
    def run(self, context: CheckContext) -> CheckResult | Sequence[CheckResult]:
        """Execute one check using the provided context.

        Args:
            context: Shared execution context.

        Returns:
            One result or a list of results from this check.
        """


@dataclass(frozen=True)
class CheckReport:
    """Aggregated report generated by `CheckRunner`.

    Args:
        ingestion_id: Ingestion execution identifier.
        generated_at: UTC timestamp when report was generated.
        fail_on: Severity threshold used for non-zero exit code.
        exit_code: Gate-friendly exit code (`0` pass, `1` fail).
        summary: Aggregated counts by status/severity.
        results: Ordered tuple of check results.
    """

    ingestion_id: int | None
    generated_at: datetime
    fail_on: Severity | None
    exit_code: int
    summary: dict[str, int]
    results: tuple[CheckResult, ...]

    def to_dict(self) -> dict[str, Any]:
        """Convert report to JSON-serializable mapping."""

        return {
            "ingestion_id": self.ingestion_id,
            "generated_at": self.generated_at.isoformat(),
            "fail_on": self.fail_on.value if self.fail_on else None,
            "exit_code": self.exit_code,
            "summary": dict(self.summary),
            "results": [result.to_dict() for result in self.results],
        }


def _severity_rank(value: Severity) -> int:
    """Return comparable integer rank for severity values."""

    order = {
        Severity.INFO: 1,
        Severity.WARNING: 2,
        Severity.ERROR: 3,
    }
    return order[value]


def _normalize_check_output(
    check_output: CheckResult | Sequence[CheckResult],
) -> list[CheckResult]:
    """Normalize one check output into a list of `CheckResult`."""

    if isinstance(check_output, CheckResult):
        return [check_output]
    return list(check_output)


class CheckRunner:
    """Execute a list of checks and generate one consolidated report."""

    def __init__(
        self,
        checks: Iterable[Check],
        *,
        fail_on: Severity | None = Severity.ERROR,
        persist_results: bool = False,
        replace_existing_results: bool = True,
        default_source_id: str | None = None,
    ) -> None:
        """Initialize check runner.

        Args:
            checks: Ordered iterable of checks to execute.
            fail_on: Severity threshold for gate failure. Use `None` to always
                return exit code `0`.
            persist_results: When `True`, persist report rows in
                `backend.app.models.dq_results.DQCheckResult`.
            replace_existing_results: When persisting, delete existing rows for
                `ingestion_id` before inserting current results.
            default_source_id: Optional fallback `source_id` for persisted rows.
        """

        self._checks = tuple(checks)
        self._fail_on = fail_on
        self._persist_results = persist_results
        self._replace_existing_results = replace_existing_results
        self._default_source_id = default_source_id

    def run(self, context: CheckContext) -> CheckReport:
        """Run configured checks and return one report.

        Args:
            context: Check execution context.

        Returns:
            Consolidated report with result list, summary and exit code.
        """

        collected: list[CheckResult] = []
        for check in self._checks:
            try:
                output = check.run(context)
                results = _normalize_check_output(output)
                for result in results:
                    if result.ingestion_id is None:
                        result.ingestion_id = context.ingestion_id
                    collected.append(result)
            except Exception as exc:  # pragma: no cover - defensive path
                collected.append(
                    CheckResult(
                        check_id=getattr(check, "check_id", check.__class__.__name__),
                        status=CheckStatus.FAIL,
                        severity=Severity.ERROR,
                        message=(
                            "Falha inesperada ao executar check. Como corrigir: "
                            "revisar stacktrace e tratamento de excecao do check."
                        ),
                        ingestion_id=context.ingestion_id,
                        evidence={
                            "exception_type": type(exc).__name__,
                            "exception_message": str(exc),
                        },
                    )
                )

        if self._persist_results:
            try:
                session = context.require_resource("session")
                persisted_count = persist_check_results(
                    session,
                    ingestion_id=context.ingestion_id,
                    results=collected,
                    replace_existing=self._replace_existing_results,
                    default_source_id=self._default_source_id,
                )
                context.metadata["dq_persisted_count"] = persisted_count
            except Exception as exc:
                collected.append(
                    CheckResult(
                        check_id="dq.persist_results",
                        status=CheckStatus.FAIL,
                        severity=Severity.ERROR,
                        message=(
                            "Falha ao persistir resultados de DQ. Como corrigir: "
                            "validar tabela dq_check_result e sessao de banco."
                        ),
                        ingestion_id=context.ingestion_id,
                        evidence={
                            "exception_type": type(exc).__name__,
                            "exception_message": str(exc),
                        },
                    )
                )

        summary = _build_summary(collected)
        exit_code = _compute_exit_code(collected, self._fail_on)
        return CheckReport(
            ingestion_id=context.ingestion_id,
            generated_at=datetime.now(timezone.utc),
            fail_on=self._fail_on,
            exit_code=exit_code,
            summary=summary,
            results=tuple(collected),
        )


def _build_summary(results: Sequence[CheckResult]) -> dict[str, int]:
    """Aggregate result counts by status and severity."""

    summary = {
        "total": len(results),
        "pass": 0,
        "fail": 0,
        "skip": 0,
        "info": 0,
        "warning": 0,
        "error": 0,
    }
    for result in results:
        summary[result.status.value] += 1
        summary[result.severity.value] += 1
    return summary


def _compute_exit_code(results: Sequence[CheckResult], fail_on: Severity | None) -> int:
    """Compute gate-friendly exit code from results and severity threshold."""

    if fail_on is None:
        return 0
    threshold = _severity_rank(fail_on)
    for result in results:
        if result.status != CheckStatus.FAIL:
            continue
        if _severity_rank(result.severity) >= threshold:
            return 1
    return 0


def _resolve_source_id(result: CheckResult, default_source_id: str | None) -> str | None:
    """Resolve best source identifier from lineage payload or fallback value.

    Args:
        result: One check result with optional lineage payload.
        default_source_id: Optional fallback source identifier.

    Returns:
        Canonicalized source identifier or `None` when unavailable.
    """

    lineage_source = result.lineage.get("source_id")
    if isinstance(lineage_source, str) and lineage_source.strip():
        return lineage_source.strip()

    if isinstance(default_source_id, str) and default_source_id.strip():
        return default_source_id.strip()

    return None


def _resolve_lineage_ref_id(lineage_payload: Mapping[str, Any]) -> int | None:
    """Extract optional lineage reference identifier from payload.

    Args:
        lineage_payload: Lineage payload generated by one check.

    Returns:
        Positive integer lineage id, or `None` when absent/invalid.
    """

    raw_value = lineage_payload.get("lineage_ref_id")
    if raw_value is None:
        raw_value = lineage_payload.get("lineage_id")
    try:
        if raw_value is None:
            return None
        parsed = int(raw_value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed > 0 else None


def persist_check_results(
    session: Any,
    *,
    ingestion_id: int | None,
    results: Sequence[CheckResult],
    replace_existing: bool = True,
    default_source_id: str | None = None,
) -> int:
    """Persist DQ check results in backend table `dq_check_result`.

    Args:
        session: SQLModel session connected to backend database.
        ingestion_id: Ingestion identifier for dedup/persistence scope.
        results: Report results to persist.
        replace_existing: Delete previous rows for this ingestion before insert.
        default_source_id: Optional fallback source identifier for rows.

    Returns:
        Number of persisted rows.

    Raises:
        RuntimeError: If backend model dependencies are unavailable.
        Exception: Any database persistence error from session operations.
    """

    if ingestion_id is None:
        return 0

    try:
        from sqlmodel import select
        from app.models.dq_results import DQCheckResult, DQCheckSeverity, DQCheckStatus, now_utc
    except ModuleNotFoundError as exc:  # pragma: no cover - depends on caller PYTHONPATH
        raise RuntimeError(
            "Dependencia de backend indisponivel para persistencia de DQ. "
            "Como corrigir: garantir import de app.models.dq_results."
        ) from exc

    if replace_existing:
        existing_rows = session.exec(
            select(DQCheckResult).where(DQCheckResult.ingestion_id == ingestion_id)
        ).all()
        for row in existing_rows:
            session.delete(row)
        session.flush()

    persisted_count = 0
    for result in results:
        row_ingestion_id = result.ingestion_id if result.ingestion_id is not None else ingestion_id
        if row_ingestion_id is None:
            continue
        row = DQCheckResult(
            ingestion_id=int(row_ingestion_id),
            source_id=_resolve_source_id(result, default_source_id=default_source_id),
            lineage_ref_id=_resolve_lineage_ref_id(result.lineage),
            check_id=result.check_id,
            severity=DQCheckSeverity(result.severity.value),
            status=DQCheckStatus(result.status.value),
            message=result.message,
            details_json=json.dumps(
                {
                    "evidence": result.evidence,
                    "lineage": result.lineage,
                },
                ensure_ascii=False,
                sort_keys=True,
            ),
            created_at=now_utc(),
        )
        session.add(row)
        persisted_count += 1

    session.commit()
    return persisted_count


def render_report_json(report: CheckReport) -> str:
    """Render a report in JSON format.

    Args:
        report: Report produced by `CheckRunner.run`.

    Returns:
        JSON string with summary and all check results.
    """

    return json.dumps(report.to_dict(), ensure_ascii=False, indent=2) + "\n"


def render_report_markdown(report: CheckReport) -> str:
    """Render a report in Markdown format.

    Args:
        report: Report produced by `CheckRunner.run`.

    Returns:
        Markdown string with header summary and result table.
    """

    lines: list[str] = []
    lines.append("# Data Quality Report")
    lines.append("")
    lines.append(f"- ingestion_id: {report.ingestion_id}")
    lines.append(f"- generated_at: {report.generated_at.isoformat()}")
    lines.append(f"- fail_on: {report.fail_on.value if report.fail_on else 'none'}")
    lines.append(f"- exit_code: {report.exit_code}")
    lines.append(f"- total: {report.summary.get('total', 0)}")
    lines.append(f"- pass: {report.summary.get('pass', 0)}")
    lines.append(f"- fail: {report.summary.get('fail', 0)}")
    lines.append(f"- skip: {report.summary.get('skip', 0)}")
    lines.append("")
    lines.append("| check_id | status | severity | message | evidence | lineage |")
    lines.append("| --- | --- | --- | --- | --- | --- |")

    for result in report.results:
        evidence_text = json.dumps(result.evidence, ensure_ascii=False, sort_keys=True)
        lineage_text = json.dumps(result.lineage, ensure_ascii=False, sort_keys=True)
        lines.append(
            "| "
            + " | ".join(
                [
                    result.check_id,
                    result.status.value,
                    result.severity.value,
                    result.message.replace("|", "\\|"),
                    evidence_text.replace("|", "\\|"),
                    lineage_text.replace("|", "\\|"),
                ]
            )
            + " |"
        )

    return "\n".join(lines) + "\n"


def parse_fail_on(value: str) -> Severity | None:
    """Parse CLI fail-on option to severity threshold.

    Args:
        value: CLI value (`info`, `warning`, `error`, `none`).

    Returns:
        Severity threshold or `None` when gate should not fail.

    Raises:
        ValueError: If value is unsupported.
    """

    normalized = str(value or "").strip().lower()
    if normalized == "none":
        return None
    try:
        return Severity(normalized)
    except ValueError as exc:
        raise ValueError(
            "Valor invalido para fail_on. Como corrigir: usar info|warning|error|none."
        ) from exc
