import type { AgeAnalysisResponse } from "../../../types/dashboard";

const defaultFaixas = {
  faixa_18_25: { volume: 5, pct: 50 },
  faixa_26_40: { volume: 3, pct: 30 },
  faixa_18_40: { volume: 8, pct: 80 },
  fora_18_40: { volume: 2, pct: 20 },
  sem_info_volume: 0,
  sem_info_pct_da_base: 0,
};

const defaultEvento = {
  evento_id: 1,
  evento_nome: "Evento Alpha",
  cidade: "Sao Paulo",
  estado: "SP",
  base_leads: 10,
  base_com_idade_volume: 10,
  base_bb_coberta_volume: 9,
  leads_proponente: 3,
  leads_ativacao: 7,
  leads_canal_desconhecido: 0,
  clientes_bb_volume: 4,
  clientes_bb_pct: 40,
  nao_clientes_bb_volume: 5,
  nao_clientes_bb_pct: 50,
  bb_indefinido_volume: 1,
  cobertura_bb_pct: 90,
  faixa_dominante: "faixa_18_25" as const,
  faixa_dominante_status: "resolved" as const,
  faixas: defaultFaixas,
};

export function buildAgeAnalysisFixture(overrides: Partial<AgeAnalysisResponse> = {}): AgeAnalysisResponse {
  return {
    version: 2,
    generated_at: "2026-03-07T12:00:00Z",
    age_reference_date: "2026-03-07",
    filters: {
      data_inicio: null,
      data_fim: null,
      evento_id: null,
    },
    por_evento: [defaultEvento],
    consolidado: {
      base_total: 10,
      base_com_idade_volume: 10,
      base_bb_coberta_volume: 9,
      leads_proponente: 3,
      leads_ativacao: 7,
      leads_canal_desconhecido: 0,
      clientes_bb_volume: 4,
      clientes_bb_pct: 40,
      nao_clientes_bb_volume: 5,
      nao_clientes_bb_pct: 50,
      bb_indefinido_volume: 1,
      cobertura_bb_pct: 90,
      faixas: defaultFaixas,
      top_eventos: [
        {
          evento_id: 1,
          evento_nome: "Evento Alpha",
          base_leads: 10,
          faixa_dominante: "faixa_18_25",
        },
      ],
      media_por_evento: 10,
      mediana_por_evento: 10,
      concentracao_top3_pct: 100,
      faixa_dominante_status: "resolved",
    },
    qualidade_consolidado: {
      base_vinculos: 10,
      sem_cpf_volume: 0,
      sem_cpf_pct: 0,
      sem_data_nascimento_volume: 0,
      sem_data_nascimento_pct: 0,
      sem_nome_completo_volume: 0,
      sem_nome_completo_pct: 0,
    },
    qualidade_por_origem: [
      {
        source_kind: "ativacao",
        label: "Ativacao (captacao)",
        base_vinculos: 7,
        sem_cpf_volume: 0,
        sem_cpf_pct: 0,
        sem_data_nascimento_volume: 0,
        sem_data_nascimento_pct: 0,
        sem_nome_completo_volume: 0,
        sem_nome_completo_pct: 0,
      },
    ],
    confianca_consolidado: {
      base_vinculos: 10,
      base_com_idade_volume: 10,
      base_bb_coberta_volume: 9,
      dedupe_candidate_volume: 11,
      dedupe_suppressed_volume: 1,
      dedupe_suppressed_pct: 9.09,
      event_name_candidate_volume: 2,
      ambiguous_event_name_volume: 0,
      ambiguous_event_name_pct: 0,
      event_name_missing_volume: 0,
      event_name_missing_pct: 0,
      evento_nome_backfill_habilitado: true,
      lineage_mix: [
        {
          source_kind: "ativacao",
          label: "Ativacao (captacao)",
          volume: 7,
          pct: 70,
        },
        {
          source_kind: "lead_batch",
          label: "Importacao (pipeline)",
          volume: 3,
          pct: 30,
        },
      ],
    },
    insights: {
      resumo: ["Resumo sintetico dos numeros do filtro atual."],
      alertas: [],
      flags: [],
    },
    ...overrides,
  };
}
