"""init"""

revision = '289b4605dc23'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlmodel


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('lote', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diretoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('formulario_landing_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('html_conteudo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('css_conteudo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_salesforce', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('sobrenome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('id_salesforce')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('territorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipo_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('chave_c', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('diretoria_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diretoria_id'], ['diretoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_c'),
    sa.UniqueConstraint('email')
    )
    op.create_table('subtipo_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convidado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_associado_id', sa.Integer(), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('cpf', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('externo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_associado_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thumbnail', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('divisao_demandante', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('qr_code_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=False),
    sa.Column('data_inicio_prevista', sa.Date(), nullable=True),
    sa.Column('data_inicio_realizada', sa.Date(), nullable=True),
    sa.Column('data_fim_prevista', sa.Date(), nullable=True),
    sa.Column('data_fim_realizada', sa.Date(), nullable=True),
    sa.Column('publico_projetado', sa.Integer(), nullable=True),
    sa.Column('publico_realizado', sa.Integer(), nullable=True),
    sa.Column('concorrencia', sa.Boolean(), nullable=False),
    sa.Column('cidade', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('agencia_id', sa.Integer(), nullable=False),
    sa.Column('diretoria_id', sa.Integer(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('subtipo_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PREVISTO', 'REALIZADO', 'CANCELADO', 'EM_ANDAMENTO', name='statusevento'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agencia_id'], ['agencia.id'], ),
    sa.ForeignKeyConstraint(['diretoria_id'], ['diretoria.id'], ),
    sa.ForeignKeyConstraint(['gestor_id'], ['funcionario.id'], ),
    sa.ForeignKeyConstraint(['subtipo_id'], ['subtipo_evento.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('BB', 'NPBB', 'AGENCIA', name='usuariotipo'), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('agencia_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agencia_id'], ['agencia.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ativacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mensagem_qrcode', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=True),
    sa.Column('redireciona_pesquisa', sa.Boolean(), nullable=False),
    sa.Column('checkin_unico', sa.Boolean(), nullable=False),
    sa.Column('termo_uso', sa.Boolean(), nullable=False),
    sa.Column('gera_cupom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cota_cortesia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('diretoria_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diretoria_id'], ['diretoria.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evento_territorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('territorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['territorio_id'], ['territorio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulario_lead_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=240), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('url_landing', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('url_promotor', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('url_questionario', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('url_api', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['formulario_landing_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionario_pagina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ativacao_lead',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativacao_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ativacao_id'], ['ativacao.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('convite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cota_id', sa.Integer(), nullable=False),
    sa.Column('convidado_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_convidador_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['convidado_id'], ['convidado.id'], ),
    sa.ForeignKeyConstraint(['cota_id'], ['cota_cortesia.id'], ),
    sa.ForeignKeyConstraint(['funcionario_convidador_id'], ['funcionario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cupom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativacao_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ativacao_id'], ['ativacao.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('formulario_lead_campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('nome_campo', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['formulario_lead_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativacao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('premio', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('titulo_feedback', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('texto_feedback', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['ativacao_id'], ['ativacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativacao_id')
    )
    op.create_table('investimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('PATROCINIO', 'PROMOCAO', name='tipoinvestimento'), nullable=False),
    sa.Column('descricao', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ativacao_id'], ['ativacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionario_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pagina_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('tipo', sa.Enum('ABERTA_TEXTO_SIMPLES', 'ABERTA_TEXTO_AREA', 'OBJETIVA_UNICA', 'OBJETIVA_MULTIPLA', 'DATA', 'AVALIACAO', 'NUMERICA', name='tipopergunta'), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pagina_id'], ['questionario_pagina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionario_resposta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('ativacao_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ativacao_id'], ['ativacao.id'], ),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('termo_uso_ativacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativacao_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ativacao_id'], ['ativacao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativacao_id')
    )
    op.create_table('questionario_opcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('valor_numerico', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_id'], ['questionario_pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionario_resposta_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('valor_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valor_numerico', sa.Numeric(), nullable=True),
    sa.Column('valor_data', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['pergunta_id'], ['questionario_pergunta.id'], ),
    sa.ForeignKeyConstraint(['resposta_id'], ['questionario_resposta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionario_resposta_opcao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta_pergunta_id', sa.Integer(), nullable=False),
    sa.Column('opcao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opcao_id'], ['questionario_opcao.id'], ),
    sa.ForeignKeyConstraint(['resposta_pergunta_id'], ['questionario_resposta_pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionario_resposta_opcao')
    op.drop_table('questionario_resposta_pergunta')
    op.drop_table('questionario_opcao')
    op.drop_table('termo_uso_ativacao')
    op.drop_table('questionario_resposta')
    op.drop_table('questionario_pergunta')
    op.drop_table('investimento')
    op.drop_table('gamificacao')
    op.drop_table('formulario_lead_campo')
    op.drop_table('cupom')
    op.drop_table('convite')
    op.drop_table('ativacao_lead')
    op.drop_table('questionario_pagina')
    op.drop_table('formulario_lead_config')
    op.drop_table('evento_territorio')
    op.drop_table('evento_tag')
    op.drop_table('cota_cortesia')
    op.drop_table('ativacao')
    op.drop_table('usuario')
    op.drop_table('evento')
    op.drop_table('convidado')
    op.drop_table('subtipo_evento')
    op.drop_table('funcionario')
    op.drop_table('tipo_evento')
    op.drop_table('territorio')
    op.drop_table('tag')
    op.drop_table('lead')
    op.drop_table('formulario_landing_template')
    op.drop_table('diretoria')
    op.drop_table('agencia')
    # ### end Alembic commands ###
