"""add campo DOMlogo_url  em AGENCIAS"""

revision = '6250e180a2f0'
down_revision = '68a1a5b9becb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlmodel


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencia', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agencia', 'logo_url')
    # ### end Alembic commands ###
