"""add campo DOMINIO  em AGENCIAS"""

revision = '68a1a5b9becb'
down_revision = '289b4605dc23'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlmodel


def upgrade() -> None:
    # Limpeza de tabelas legadas (ordem ajustada e com CASCADE)
    legacy_tables = [
        "post_hashtags",
        "hashtags",
        "post_mentions",
        "mentions",
        "comments",
        "metrics_snapshots",
        "media_assets",
        "deliverable_evidence",
        "deliverable_periods",
        "deliverables",
        "posts",
        "social_profiles",
        "contracts",
        "campaigns",
        "endorsees",
    ]
    for tbl in legacy_tables:
        op.execute(f'DROP TABLE IF EXISTS "{tbl}" CASCADE')

    op.add_column('agencia', sa.Column('dominio', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.execute(
        "UPDATE agencia SET dominio = lower(regexp_replace(nome, '\\s+', '', 'g')) WHERE dominio IS NULL"
    )
    op.alter_column('agencia', 'dominio', existing_type=sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False)
    op.create_unique_constraint('uq_agencia_dominio', 'agencia', ['dominio'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_agencia_dominio', 'agencia', type_='unique')
    op.drop_column('agencia', 'dominio')
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('start_date <= end_date', name='campaigns_dates_chk'),
    sa.PrimaryKeyConstraint('id', name='campaigns_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('deliverable_periods',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('deliverable_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity_required', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('period_start <= period_end', name='deliverable_periods_dates_chk'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], name='deliverable_periods_deliverable_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deliverable_periods_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('uq_deliverable_period', 'deliverable_periods', ['deliverable_id', 'period_start', 'period_end'], unique=True)
    op.create_index('idx_deliverable_periods_lookup', 'deliverable_periods', ['deliverable_id', 'period_start', 'period_end'], unique=False)
    op.create_index('deliverable_periods_range_gist', 'deliverable_periods', [sa.text("daterange(period_start, period_end, '[]'::text)")], unique=False, postgresql_using='gist')
    op.create_index('deliverable_periods_deliverable_idx', 'deliverable_periods', ['deliverable_id'], unique=False)
    op.create_table('post_hashtags',
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hashtag_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], name='post_hashtags_hashtag_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_hashtags_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'hashtag_id', name='post_hashtags_pkey')
    )
    op.create_table('deliverable_evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('deliverable_period_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('matched', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('matched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'partial', 'met', 'missed', name='deliverable_status_t'), server_default=sa.text("'pending'::deliverable_status_t"), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deliverable_period_id'], ['deliverable_periods.id'], name='deliverable_evidence_deliverable_period_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='deliverable_evidence_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deliverable_evidence_pkey'),
    sa.UniqueConstraint('deliverable_period_id', 'post_id', name='deliverable_evidence_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('uq_deliverable_evidence_period_post', 'deliverable_evidence', ['deliverable_period_id', 'post_id'], unique=True)
    op.create_index('evidence_status_idx', 'deliverable_evidence', ['status', 'matched'], unique=False)
    op.create_index('evidence_period_idx', 'deliverable_evidence', ['deliverable_period_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumb_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_video', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='media_assets_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='media_assets_pkey'),
    sa.UniqueConstraint('post_id', 'position', name='media_assets_post_pos_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_media_assets_post', 'media_assets', ['post_id'], unique=False)
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('taken_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saved_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='metrics_snapshots_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='metrics_snapshots_pkey'),
    sa.UniqueConstraint('post_id', 'taken_at', name='metrics_unique_per_post_ts', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('metrics_post_taken_idx', 'metrics_snapshots', ['post_id', sa.text('taken_at DESC')], unique=False)
    op.create_index('idx_metrics_snapshots_post_time', 'metrics_snapshots', ['post_id', sa.text('taken_at DESC')], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('mentions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('platform', postgresql.ENUM('instagram', name='platform_t'), server_default=sa.text("'instagram'::platform_t"), autoincrement=False, nullable=False),
    sa.Column('platform_user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mentions_pkey'),
    sa.UniqueConstraint('platform', 'username', name='mentions_platform_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('platform', 'username', name='mentions_platform_username_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('deliverables',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('platform', postgresql.ENUM('instagram', name='platform_t'), server_default=sa.text("'instagram'::platform_t"), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('post', 'story', 'reel', 'comment', 'other', name='deliverable_type_t'), autoincrement=False, nullable=False),
    sa.Column('quantity_required', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('periodicity', postgresql.ENUM('none', 'weekly', 'monthly', 'quarterly', name='periodicity_t'), server_default=sa.text("'monthly'::periodicity_t"), autoincrement=False, nullable=False),
    sa.Column('hashtags_required', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('mentions_required', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('keywords_required', postgresql.ARRAY(sa.TEXT()), server_default=sa.text("'{}'::text[]"), autoincrement=False, nullable=True),
    sa.Column('tracking_query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='deliverables_contract_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='deliverables_pkey')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('platform', postgresql.ENUM('instagram', name='platform_t'), server_default=sa.text("'instagram'::platform_t"), autoincrement=False, nullable=False),
    sa.Column('platform_comment_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_platform_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parent_platform_comment_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='comments_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey'),
    sa.UniqueConstraint('platform', 'platform_comment_id', name='comments_platform_id_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('platform', 'platform_comment_id', name='comments_platform_platform_comment_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('idx_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_index('comments_raw_gin', 'comments', ['raw'], unique=False, postgresql_ops={'raw': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index('comments_post_idx', 'comments', ['post_id'], unique=False)
    op.create_index('comments_parent_idx', 'comments', ['parent_platform_comment_id'], unique=False, postgresql_where='(parent_platform_comment_id IS NOT NULL)')
    op.create_index('comments_created_idx', 'comments', ['created_at'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('platform', postgresql.ENUM('instagram', name='platform_t'), autoincrement=False, nullable=False),
    sa.Column('platform_media_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shortcode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('caption', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_type', postgresql.ENUM('image', 'video', 'carousel', 'story', 'reel', name='media_type_t'), autoincrement=False, nullable=False),
    sa.Column('posted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('saved_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_pinned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('collected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('posted_date', sa.DATE(), sa.Computed("((posted_at AT TIME ZONE 'UTC'::text))::date", persisted=True), autoincrement=False, nullable=True),
    sa.Column('posted_month', sa.DATE(), sa.Computed("(date_trunc('month'::text, (posted_at AT TIME ZONE 'UTC'::text)))::date", persisted=True), autoincrement=False, nullable=True),
    sa.Column('caption_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple'::regconfig, immutable_unaccent(COALESCE(caption, ''::text)))", persisted=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], name='posts_profile_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey'),
    sa.UniqueConstraint('platform', 'platform_media_id', name='posts_platform_media_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('platform', 'platform_media_id', name='posts_platform_platform_media_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index('posts_raw_gin', 'posts', ['raw'], unique=False, postgresql_ops={'raw': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index('posts_profile_idx', 'posts', ['profile_id'], unique=False)
    op.create_index('posts_posted_at_desc', 'posts', [sa.text('posted_at DESC')], unique=False)
    op.create_index('idx_posts_profile_postedat', 'posts', ['profile_id', sa.text('posted_at DESC')], unique=False)
    op.create_index('idx_posts_posted_month', 'posts', ['posted_month'], unique=False)
    op.create_index('idx_posts_posted_date', 'posts', ['posted_date'], unique=False)
    op.create_index('idx_posts_mediatype', 'posts', ['media_type'], unique=False)
    op.create_table('post_mentions',
    sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mention_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mentions.id'], name='post_mentions_mention_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_mentions_post_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'mention_id', name='post_mentions_pkey')
    )
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('endorsee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('monthly_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'active', 'paused', 'ended', name='contract_status_t'), server_default=sa.text("'active'::contract_status_t"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.CheckConstraint('start_date <= end_date', name='contracts_dates_chk'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name='contracts_campaign_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['endorsee_id'], ['endorsees.id'], name='contracts_endorsee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contracts_pkey')
    )
    op.create_table('social_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('endorsee_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('platform', postgresql.ENUM('instagram', name='platform_t'), autoincrement=False, nullable=False),
    sa.Column('platform_user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('followers_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['endorsee_id'], ['endorsees.id'], name='social_profiles_endorsee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='social_profiles_pkey'),
    sa.UniqueConstraint('platform', 'platform_user_id', name='social_profiles_platform_platform_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('platform', 'platform_user_id', name='social_profiles_platform_user_uniq', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('social_profiles_endorsee_idx', 'social_profiles', ['endorsee_id'], unique=False)
    op.create_index('idx_social_profiles_platform_username', 'social_profiles', ['platform', 'username'], unique=False)
    op.create_table('endorsees',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expertise', postgresql.ENUM('Surf', 'Skate', 'Canoagem', 'Volei de quadra', 'volei de praia', 'eSports', 'Corrida de Rua', 'Influencia Digital', name='expertise_t'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='endorsees_pkey')
    )
    op.create_table('hashtags',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hashtags_pkey'),
    sa.UniqueConstraint('name', name='hashtags_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
